<a href="https://colab.research.google.com/github/njwbilll/Tugas-3_Practical-Linear-Algebra-O-Reilly-_Najwa-Bilqis-Al-Khalidah/blob/main/09_Orthogonal_Matrices_and_QR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 9: Orthogonal Matrices and QR Decomposition

**Referensi:** Practical Linear Algebra for Data Science (Mike X Cohen)

***

## Ringkasan Materi
Matriks ortogonal adalah matriks yang kolom kolomnya saling tegak lurus (ortogonal) dan memiliki panjang unit (normal). Karena properti unik ini, perkalian matriks ortogonal dengan dirinya sendiri yang ditranspose akan menghasilkan matriks identitas. Dekomposisi QR adalah proses faktorisasi matriks menjadi matriks ortogonal (Q) dan matriks segitiga atas (R), yang sangat stabil untuk komputasi numerik.

### Topik yang Dibahas:
1. Definisi dan Sifat Matriks Ortogonal
2. Algoritma Gram Schmidt
3. Dekomposisi QR
4. Penggunaan QR untuk Inversi Matriks


In [1]:
import numpy as np

# 1. Memeriksa Matriks Ortogonal
Q = np.array([[1, 0],
              [0, -1]]) # Matriks ortogonal sederhana

print("Perkalian Q transpose dengan Q (Harus identitas):\n", Q.T @ Q)

# 2. Dekomposisi QR
A = np.array([[1, 2], [3, 4], [5, 6]])
Q_qr, R_qr = np.linalg.qr(A)

print("\nMatriks Q (Ortogonal):\n", Q_qr)
print("\nMatriks R (Segitiga Atas):\n", R_qr)
print("\nVerifikasi A = QR:\n", Q_qr @ R_qr)


Perkalian Q transpose dengan Q (Harus identitas):
 [[1 0]
 [0 1]]

Matriks Q (Ortogonal):
 [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]

Matriks R (Segitiga Atas):
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]

Verifikasi A = QR:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


***
## Geometri dan Gram Schmidt

### Penjelasan Teori
Gram Schmidt adalah metode untuk mengambil sekumpulan vektor yang bebas linear dan mengubahnya menjadi sekumpulan vektor ortogonal. Ini adalah langkah kunci di balik dekomposisi QR.




In [2]:
# Implementasi Gram Schmidt sederhana untuk dua vektor
v1 = np.array([1, 1, 0])
v2 = np.array([1, 0, 1])

# Vektor ortogonal pertama
u1 = v1

# Vektor ortogonal kedua
u2 = v2 - (np.dot(v2, u1) / np.dot(u1, u1)) * u1

print("Vektor ortogonal hasil Gram Schmidt:\n", u1, "dan", u2)
print("Cek dot product (harus nol):", np.dot(u1, u2))


Vektor ortogonal hasil Gram Schmidt:
 [1 1 0] dan [ 0.5 -0.5  1. ]
Cek dot product (harus nol): 0.0


***
## Mengapa QR lebih baik daripada Invers?

### Penjelasan Teori
Dalam komputasi, menghitung invers matriks secara langsung (menggunakan `inv`) sering kali tidak stabil secara numerik jika matriksnya hampir singular. Dekomposisi QR memberikan solusi yang jauh lebih robust karena menghindari invers eksplisit dengan memanfaatkan properti ortogonalitas dari matriks Q.