<a href="https://colab.research.google.com/github/njwbilll/Tugas-3_Practical-Linear-Algebra-O-Reilly-_Najwa-Bilqis-Al-Khalidah/blob/main/10_Row_Reduction_LU_Decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 10: Row Reduction and LU Decomposition

**Referensi:** Practical Linear Algebra for Data Science (Mike X Cohen)

***

## Ringkasan Materi
Bab ini mempelajari bagaimana komputer menyelesaikan sistem persamaan linear $Ax = b$. Kita mengeksplorasi teknik reduksi baris (row reduction) untuk mengubah matriks menjadi bentuk eselon baris, serta dekomposisi LU yang memecah matriks menjadi faktor segitiga bawah (Lower) dan segitiga atas (Upper).

### Topik yang Dibahas:
1. Konversi sistem persamaan menjadi matriks
2. Eliminasi Gaussian dan Gauss Jordan
3. Inversi matriks menggunakan reduksi baris
4. Dekomposisi LU dan matriks permutasi


In [1]:
import numpy as np
import scipy.linalg as la

# 1. Sistem Persamaan Linear: Ax = b
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])
b = np.array([4, 5, 6])

# 2. Eliminasi Gaussian (Selesaikan Ax = b)
x = la.solve(A, b)
print("Solusi sistem persamaan x:", x)


Solusi sistem persamaan x: [  6.  15. -23.]


***
## LU Decomposition

### Penjelasan Teori
Dekomposisi LU memecah matriks A menjadi A = P * L * U, di mana P adalah matriks permutasi (untuk menangani pertukaran baris), L adalah matriks segitiga bawah, dan U adalah matriks segitiga atas. Ini jauh lebih efisien daripada menghitung invers matriks secara langsung saat menyelesaikan banyak sistem dengan nilai b yang berbeda.



In [2]:
# Melakukan LU Decomposition dengan pivoting (P)
P, L, U = la.lu(A)

print("Matriks Permutasi P:\n", P)
print("Matriks Segitiga Bawah L:\n", L)
print("Matriks Segitiga Atas U:\n", U)

# Verifikasi A = PLU
print("\nVerifikasi A = PLU:\n", np.round(P @ L @ U))


Matriks Permutasi P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks Segitiga Bawah L:
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
Matriks Segitiga Atas U:
 [[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]

Verifikasi A = PLU:
 [[ 2.  1.  1.]
 [ 1.  3.  2.]
 [ 1. -0.  0.]]


***
## Inversi melalui Gauss Jordan

### Penjelasan Teori
Metode Gauss Jordan melibatkan pembuatan matriks augmented [A | I], kemudian melakukan operasi baris elementer hingga sisi kiri menjadi matriks identitas I. Sisi kanan matriks augmented tersebut kemudian berubah menjadi invers dari A.




In [3]:
# Membuat matriks augmented [A | I]
I = np.eye(len(A))
augmented = np.hstack((A, I))

print("Matriks Augmented [A | I]:\n", augmented)
# Komputasi reduksi baris secara manual dapat dilakukan dengan iterasi,
# namun di industri, kita menggunakan library scipy untuk stabilitas numerik.


Matriks Augmented [A | I]:
 [[2. 1. 1. 1. 0. 0.]
 [1. 3. 2. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]
